name: Release
on:
  release:
    types: created
jobs:
  Linux:
    runs-on: ubuntu-18.04
    container: shatur95/crow-translate:ubuntu-18.04
    steps:
    - name: Clone repo
      uses: actions/checkout@v1
      with:
        submodules: recursive
        fetch-depth: 5

    - name: Create package
      run: |
        cp -r dist/unix/apt/debian debian
        ver=$(awk 'NR==1 {print $2}' debian/changelog | sed 's/[()]//g')
        tar czfv ../crow-translate_${ver%-*}.orig.tar.gz .github *
        debuild -i -us -uc
        mv ../crow-translate_${ver}_amd64.deb ../crow-translate-${ver%-*}-amd64.deb

    - name: Upload
      uses: AButler/upload-release-assets@v1.0
      with:
        files: '../*.deb'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  Windows:
    runs-on: windows-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v1
      with:
        arch: win64_mingw73

    - name: Enable Git symlinks
      run: git config --global core.symlinks true

    - name: Clone repo
      uses: actions/checkout@v1
      with:
        submodules: recursive
        fetch-depth: 5

    - name: Build
      run: |
        qmake "DEFINES += PORTABLE_MODE GLOBAL_SHORTCUTS"
        make

    - name: Bundle libraries
      run: |
        mkdir dist/windows/release
        mv release/crow.exe dist/windows/release
        windeployqt.exe dist/windows/release/crow.exe
        cp $env:Qt5_Dir/bin/libgcc_s_seh-1.dll dist/windows/release/
        cp $env:Qt5_Dir/bin/libstdc++-6.dll dist/windows/release/
        cp $env:Qt5_Dir/bin/libwinpthread-1.dll dist/windows/release/
        cp "C:\Program Files\Git\mingw64\bin\libcrypto-1_1-x64.dll" dist/windows/release/
        cp "C:\Program Files\Git\mingw64\bin\libssl-1_1-x64.dll" dist/windows/release/

    - name: Create installer
      run: makensis dist/windows/installer-script.nsi
      
    - name: Create archive
      run: 7z a dist/windows/crow-translate-$(git describe --tags)-win64.7z ./dist/windows/release/*

    - name: Upload
      uses: AButler/upload-release-assets@v1.0
      with:
        files: 'dist/windows/*.exe,dist/windows/*.7z'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
